title: Paweł Sulewski
logo: photo_cropped.jpg
description: |
  <a href="https://medium.com/@sulewski12" target="_blank">
    ✍️ Visit my Medium
  </a>
show_downloads: false
theme: jekyll-theme-minimal
